"""WSGI entry point for the GALINT Flask application."""
from galint_flask import create_app

app = create_app()


def _load_migration_funcs():
    try:
        from flask_migrate import init as _migrate_init, migrate as _migrate, upgrade as _upgrade
    except Exception:
        print("Flask-Migrate não encontrado. Instale com: pip install Flask-Migrate")
        raise

    return _migrate_init, _migrate, _upgrade


def _run_migrations(app):
    """Inicliza pasta de migrations (se necessário), gera e aplica migration.

    Usa API programática do Flask-Migrate para suportar ambientes sem CLI.
    """
    from pathlib import Path

    _migrate_init, _migrate, _upgrade = _load_migration_funcs()
    migrations_dir = Path(__file__).resolve().parent / "migrations"
    try:
        if not migrations_dir.exists():
            print("Inicializando pasta de migrations...")
            _migrate_init(directory=str(migrations_dir))

        print("Gerando migration automática (comparando models)...")
        _migrate(message="autogenerated by app.py", directory=str(migrations_dir))

        print("Aplicando migrations (upgrade)...")
        _upgrade(directory=str(migrations_dir))
        print("Migrações aplicadas com sucesso.")
    except Exception as e:
        print(f"Erro ao executar migrações: {e}")
        raise


def _run_upgrade(app):
    """Aplica migrations existentes sem gerar novas."""
    from pathlib import Path

    _, _, _upgrade = _load_migration_funcs()
    migrations_dir = Path(__file__).resolve().parent / "migrations"
    try:
        print("Aplicando migrations pendentes (upgrade)...")
        _upgrade(directory=str(migrations_dir))
        print("Upgrade aplicado com sucesso.")
    except Exception as e:
        print(f"Erro ao aplicar upgrade: {e}")
        raise


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1 and sys.argv[1] in ("migrate", "db-migrate"):
        # Executar migrações programaticamente e sair
        with app.app_context():
            _run_migrations(app)
        sys.exit(0)

    if len(sys.argv) > 1 and sys.argv[1] in ("upgrade", "db-upgrade"):
        # Aplicar migrations existentes e sair
        with app.app_context():
            _run_upgrade(app)
        sys.exit(0)

    print("🌐 Iniciando servidor em modo HTTP")
    print("   URL: http://localhost:5000")
    print("   LAN: http://SEU_IP:5000 (ex.: http://10.0.0.245:5000)")
    app.run(host="0.0.0.0", port=5000, debug=True, use_reloader=False, threaded=True)
