"""WSGI entry point for the GALINT Flask application."""
from galint_flask import create_app

app = create_app()

# Fallback routes for foto por URL (evita 404 se blueprints nao carregarem)
try:
    from flask import request, jsonify
    from galint_flask.models import Item
    from galint_flask.extensions import db
    from galint_flask.services.item_foto_service import ItemFotoService

    def _apply_photo_from_url():
        payload = request.form if request.form else (request.json or {})
        codigo = (payload.get('codigo') or '').strip()
        image_url = (payload.get('image_url') or '').strip()
        if not codigo:
            return jsonify({'success': False, 'message': 'Codigo do item nao informado'}), 400
        if not image_url:
            return jsonify({'success': False, 'message': 'URL da imagem nao informada'}), 400
        item = Item.query.get(codigo)
        if not item:
            return jsonify({'success': False, 'message': 'Item nao encontrado'}), 404
        try:
            if item.foto_path:
                ItemFotoService.deletar_foto(item.foto_path)
            foto_path = ItemFotoService.download_foto_from_url(image_url, codigo)
            item.foto_path = foto_path
            db.session.commit()
            return jsonify({'success': True, 'message': 'Foto atualizada', 'foto_path': foto_path})
        except ValueError as exc:
            return jsonify({'success': False, 'message': str(exc)}), 400
        except Exception:
            return jsonify({'success': False, 'message': 'Falha inesperada ao atualizar foto'}), 500

    if 'foto_url_api_fallback' not in app.view_functions:
        app.add_url_rule('/api/itens/foto/url', endpoint='foto_url_api_fallback', view_func=_apply_photo_from_url, methods=['POST'])
    if 'foto_url_fallback' not in app.view_functions:
        app.add_url_rule('/itens/foto/url', endpoint='foto_url_fallback', view_func=_apply_photo_from_url, methods=['POST'])
except Exception:
    pass


def _load_migration_funcs():
    try:
        from flask_migrate import init as _migrate_init, migrate as _migrate, upgrade as _upgrade
    except Exception:
        print("Flask-Migrate não encontrado. Instale com: pip install Flask-Migrate")
        raise

    return _migrate_init, _migrate, _upgrade


def _run_migrations(app):
    """Inicliza pasta de migrations (se necessário), gera e aplica migration.

    Usa API programática do Flask-Migrate para suportar ambientes sem CLI.
    """
    from pathlib import Path

    _migrate_init, _migrate, _upgrade = _load_migration_funcs()
    migrations_dir = Path(__file__).resolve().parent / "migrations"
    try:
        if not migrations_dir.exists():
            print("Inicializando pasta de migrations...")
            _migrate_init(directory=str(migrations_dir))

        print("Gerando migration automática (comparando models)...")
        _migrate(message="autogenerated by app.py", directory=str(migrations_dir))

        print("Aplicando migrations (upgrade)...")
        _upgrade(directory=str(migrations_dir))
        print("Migrações aplicadas com sucesso.")
    except Exception as e:
        print(f"Erro ao executar migrações: {e}")
        raise


def _run_upgrade(app):
    """Aplica migrations existentes sem gerar novas."""
    from pathlib import Path

    _, _, _upgrade = _load_migration_funcs()
    migrations_dir = Path(__file__).resolve().parent / "migrations"
    try:
        print("Aplicando migrations pendentes (upgrade)...")
        _upgrade(directory=str(migrations_dir))
        print("Upgrade aplicado com sucesso.")
    except Exception as e:
        print(f"Erro ao aplicar upgrade: {e}")
        raise


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1 and sys.argv[1] in ("migrate", "db-migrate"):
        # Executar migrações programaticamente e sair
        with app.app_context():
            _run_migrations(app)
        sys.exit(0)

    if len(sys.argv) > 1 and sys.argv[1] in ("upgrade", "db-upgrade"):
        # Aplicar migrations existentes e sair
        with app.app_context():
            _run_upgrade(app)
        sys.exit(0)

    print("🌐 Iniciando servidor em modo HTTP")
    print("   URL: http://localhost:5000")
    print("   LAN: http://SEU_IP:5000 (ex.: http://10.0.0.245:5000)")
    app.run(host="0.0.0.0", port=5000, debug=True, use_reloader=False, threaded=True)
