"""autogenerated by app.py

Revision ID: 07f4c54a93e9
Revises: cfda6f296c8b
Create Date: 2026-02-10 09:31:20.881535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07f4c54a93e9'
down_revision = 'cfda6f296c8b'
branch_labels = None
depends_on = None


def upgrade():
        # Esta migration foi autogerada com operações destrutivas incompatíveis com
        # bases já em produção. Mantemos apenas ajustes seguros e idempotentes.
        op.execute(
                """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_name = 'telegram_users'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'telegram_users' AND column_name = 'can_create_item_via_telegram'
    ) THEN
        ALTER TABLE telegram_users
            ADD COLUMN can_create_item_via_telegram boolean NOT NULL DEFAULT false;
    END IF;
END $$;
"""
        )


def downgrade():
    # Sem downgrade automático: a versão original também era destrutiva e não é
    # segura para este histórico de banco.
    pass
