"""autogenerated by app.py

Revision ID: 07f4c54a93e9
Revises: cfda6f296c8b
Create Date: 2026-02-10 09:31:20.881535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07f4c54a93e9'
down_revision = 'cfda6f296c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contagem_inventario')
    op.drop_table('fornecedores')
    op.drop_table('plano_manutencao')
    op.drop_table('pedido_compra')
    op.drop_table('saidas_lote')
    op.drop_table('inventario_ciclico')
    op.drop_table('ordem_servico')
    op.drop_table('areas')
    op.drop_table('falha_equipamento')
    op.drop_table('equipamentos')
    op.drop_table('pedido_compra_itens')
    with op.batch_alter_table('ferramentas_em_uso', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'EM_USO'::character varying"))
        batch_op.drop_index(batch_op.f('idx_ferramentas_uso_matricula'))
        batch_op.drop_index(batch_op.f('idx_ferramentas_uso_patrimonio'))
        batch_op.drop_index(batch_op.f('idx_ferramentas_uso_status'))
        batch_op.create_index(batch_op.f('ix_ferramentas_em_uso_codigo_patrimonial'), ['codigo_patrimonial'], unique=False)
        batch_op.create_index(batch_op.f('ix_ferramentas_em_uso_status'), ['status'], unique=False)

    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.alter_column('unidades_por_embalagem',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('estoque_embalagens',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('estoque_unidades_soltas',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('idx_itens_categoria'))
        batch_op.drop_index(batch_op.f('idx_itens_lote'))
        batch_op.drop_index(batch_op.f('idx_itens_numero_serie'))
        batch_op.drop_column('estoque_seguranca')
        batch_op.drop_column('cmm')
        batch_op.drop_column('foto_filename')
        batch_op.drop_column('custo_unitario')
        batch_op.drop_column('ponto_pedido')
        batch_op.drop_column('classe_abc')
        batch_op.drop_column('lead_time_dias')
        batch_op.drop_column('cmm_manual')

    with op.batch_alter_table('patrimonio_ferramentas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_patrimonio_codigo'))
        batch_op.drop_index(batch_op.f('idx_patrimonio_codigo_item'))
        batch_op.drop_index(batch_op.f('idx_patrimonio_matricula'))
        batch_op.drop_index(batch_op.f('idx_patrimonio_status'))

    with op.batch_alter_table('telegram_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_create_item_via_telegram', sa.Boolean(), nullable=False, comment='Permite que o usuário cadastre itens via Telegram'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_users', schema=None) as batch_op:
        batch_op.drop_column('can_create_item_via_telegram')

    with op.batch_alter_table('patrimonio_ferramentas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_patrimonio_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_patrimonio_matricula'), ['matricula'], unique=False)
        batch_op.create_index(batch_op.f('idx_patrimonio_codigo_item'), ['codigo_item'], unique=False)
        batch_op.create_index(batch_op.f('idx_patrimonio_codigo'), ['codigo_patrimonial'], unique=False)

    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cmm_manual', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lead_time_dias', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('classe_abc', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ponto_pedido', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('custo_unitario', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('foto_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cmm', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('estoque_seguranca', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_itens_numero_serie'), ['numero_serie'], unique=False)
        batch_op.create_index(batch_op.f('idx_itens_lote'), ['lote'], unique=False)
        batch_op.create_index(batch_op.f('idx_itens_categoria'), ['categoria'], unique=False)
        batch_op.alter_column('estoque_unidades_soltas',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=3),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('estoque_embalagens',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=3),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('unidades_por_embalagem',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=3),
               existing_nullable=True)

    with op.batch_alter_table('ferramentas_em_uso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ferramentas_em_uso_status'))
        batch_op.drop_index(batch_op.f('ix_ferramentas_em_uso_codigo_patrimonial'))
        batch_op.create_index(batch_op.f('idx_ferramentas_uso_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_ferramentas_uso_patrimonio'), ['codigo_patrimonial'], unique=False)
        batch_op.create_index(batch_op.f('idx_ferramentas_uso_matricula'), ['matricula'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'EM_USO'::character varying"))

    op.create_table('pedido_compra_itens',
    sa.Column('id_pc_item', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pedido_compra_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codigo_item', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('valor_unitario', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['codigo_item'], ['itens.codigo_item'], name=op.f('pedido_compra_itens_codigo_item_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pedido_compra_id'], ['pedido_compra.id_pc'], name=op.f('pedido_compra_itens_pedido_compra_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pc_item', name=op.f('pedido_compra_itens_pkey'))
    )
    op.create_table('equipamentos',
    sa.Column('id_equipamento', sa.INTEGER(), server_default=sa.text("nextval('equipamentos_id_equipamento_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('fabricante', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('modelo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('numero_serie', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('data_aquisicao', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('foto_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id_area'], name='equipamentos_area_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_equipamento', name='equipamentos_pkey'),
    sa.UniqueConstraint('codigo', name='equipamentos_codigo_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('falha_equipamento',
    sa.Column('id_falha', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('equipamento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_falha', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('tipo_falha', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('gravidade', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('causa_raiz', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('acao_corretiva', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tempo_parada_minutos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('custo_parada', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id_equipamento'], name=op.f('falha_equipamento_equipamento_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_falha', name=op.f('falha_equipamento_pkey'))
    )
    op.create_table('areas',
    sa.Column('id_area', sa.INTEGER(), server_default=sa.text("nextval('areas_id_area_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_area', name='areas_pkey'),
    sa.UniqueConstraint('codigo', name='areas_codigo_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('ordem_servico',
    sa.Column('id_os', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('numero_os', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('equipamento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('prioridade', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('solicitante_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('responsavel_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('descricao_problema', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descricao_solucao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_abertura', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data_agendamento', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('data_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('data_conclusao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tempo_parada_minutos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('custo_estimado', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('custo_real', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id_equipamento'], name=op.f('ordem_servico_equipamento_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.matricula'], name=op.f('ordem_servico_responsavel_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.matricula'], name=op.f('ordem_servico_solicitante_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_os', name=op.f('ordem_servico_pkey')),
    sa.UniqueConstraint('numero_os', name=op.f('ordem_servico_numero_os_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('inventario_ciclico',
    sa.Column('id_inventario', sa.INTEGER(), server_default=sa.text("nextval('inventario_ciclico_id_inventario_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('numero', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('data_programada', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('data_conclusao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('responsavel_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.matricula'], name='inventario_ciclico_responsavel_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_inventario', name='inventario_ciclico_pkey'),
    sa.UniqueConstraint('numero', name='inventario_ciclico_numero_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('saidas_lote',
    sa.Column('id_saida_lote', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('saida_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entrada_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['entrada_id'], ['entradas.id_entrada'], name=op.f('saidas_lote_entrada_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['saida_id'], ['saidas.id_saida'], name=op.f('saidas_lote_saida_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_saida_lote', name=op.f('saidas_lote_pkey'))
    )
    op.create_table('pedido_compra',
    sa.Column('id_pc', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('numero_pc', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('fornecedor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_pedido', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data_prevista', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id_fornecedor'], name=op.f('pedido_compra_fornecedor_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.matricula'], name=op.f('pedido_compra_usuario_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_pc', name=op.f('pedido_compra_pkey')),
    sa.UniqueConstraint('numero_pc', name=op.f('pedido_compra_numero_pc_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('plano_manutencao',
    sa.Column('id_plano', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('equipamento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tipo_periodicidade', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('intervalo_dias', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('intervalo_horas_uso', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ultima_execucao', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('proxima_execucao', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id_equipamento'], name=op.f('plano_manutencao_equipamento_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_plano', name=op.f('plano_manutencao_pkey'))
    )
    op.create_table('fornecedores',
    sa.Column('id_fornecedor', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cnpj', sa.VARCHAR(length=18), autoincrement=False, nullable=True),
    sa.Column('lead_time_dias', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contato', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_fornecedor', name=op.f('fornecedores_pkey')),
    sa.UniqueConstraint('cnpj', name=op.f('fornecedores_cnpj_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('contagem_inventario',
    sa.Column('id_contagem', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('inventario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codigo_item', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantidade_sistema', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quantidade_contada', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('divergencia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('percentual_divergencia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('contador_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data_contagem', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('recontagem', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ajustado', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['codigo_item'], ['itens.codigo_item'], name=op.f('contagem_inventario_codigo_item_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contador_id'], ['usuarios.matricula'], name=op.f('contagem_inventario_contador_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventario_ciclico.id_inventario'], name=op.f('contagem_inventario_inventario_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_contagem', name=op.f('contagem_inventario_pkey'))
    )
    # ### end Alembic commands ###
