"""Add traceability fields to Item model

Revision ID: 616036e9b6f8
Revises: remove_old_prefs_cols
Create Date: 2026-01-31 13:42:45.952521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '616036e9b6f8'
down_revision = 'remove_old_prefs_cols'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_entrada', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('lote', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data_fabricacao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_validade', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('tipo_embalagem', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('grandeza_referencia', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('densidade', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('barcode_image_path', sa.String(length=255), nullable=True))
    
    # Criar índice para otimizar buscas por lote
    op.create_index('idx_itens_lote', 'itens', ['lote'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_itens_lote', table_name='itens')
    
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.drop_column('barcode_image_path')
        batch_op.drop_column('densidade')
        batch_op.drop_column('grandeza_referencia')
        batch_op.drop_column('tipo_embalagem')
        batch_op.drop_column('data_validade')
        batch_op.drop_column('data_fabricacao')
        batch_op.drop_column('lote')
        batch_op.drop_column('data_entrada')

    # ### end Alembic commands ###
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id_fornecedor'], name='pedido_compra_fornecedor_id_fkey', ondelete='RESTRICT'),

    # ### end Alembic commands ###

