"""Add stock ledger tables and rollout flags

Revision ID: b6f4d3a9e8c1
Revises: f8b1d9c2a6e4
Create Date: 2026-03-22
"""

from alembic import op


revision = "b6f4d3a9e8c1"
down_revision = "f8b1d9c2a6e4"
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        """
DO $$
BEGIN
  CREATE TABLE IF NOT EXISTS stock_movements (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_item varchar NOT NULL REFERENCES itens(codigo_item) ON DELETE CASCADE,
    motion_type varchar(20) NOT NULL,
    amount_base double precision NOT NULL,
    unit_type varchar(40) NULL,
    reference_type varchar(60) NULL,
    reference_id varchar(120) NULL,
    source varchar(30) NULL,
    user_id varchar NULL REFERENCES usuarios(matricula) ON DELETE SET NULL,
    metadata_json jsonb NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT chk_stock_movements_type CHECK (motion_type IN ('IN', 'OUT', 'RETURN', 'ADJUST', 'INITIAL')),
    CONSTRAINT chk_stock_movements_amount_nonzero CHECK (amount_base <> 0),
    CONSTRAINT uq_stock_movements_reference UNIQUE (codigo_item, reference_type, reference_id)
  );

  CREATE TABLE IF NOT EXISTS stock_balances (
    codigo_item varchar PRIMARY KEY REFERENCES itens(codigo_item) ON DELETE CASCADE,
    quantity_base double precision NOT NULL DEFAULT 0,
    updated_at timestamp NOT NULL DEFAULT now(),
    last_movement_id integer NULL REFERENCES stock_movements(id) ON DELETE SET NULL
  );

  CREATE INDEX IF NOT EXISTS ix_stock_movements_codigo_item ON stock_movements(codigo_item);
  CREATE INDEX IF NOT EXISTS ix_stock_movements_created_at ON stock_movements(created_at);
  CREATE INDEX IF NOT EXISTS ix_stock_movements_type ON stock_movements(motion_type);
  CREATE INDEX IF NOT EXISTS ix_stock_movements_reference ON stock_movements(reference_type, reference_id);

  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'feature_flags') THEN
    INSERT INTO feature_flags (
      flag_key,
      display_name,
      description,
      is_enabled,
      flag_type,
      default_value,
      requires_app_restart,
      min_app_version,
      created_at,
      updated_at
    )
    SELECT
      'inventory_ledger_dual_write',
      'Inventory Ledger Dual Write',
      'Espelha entradas, saídas e ajustes legados em stock_movements.',
      false,
      'boolean',
      'false',
      false,
      NULL,
      now(),
      now()
    WHERE NOT EXISTS (
      SELECT 1 FROM feature_flags WHERE flag_key = 'inventory_ledger_dual_write'
    );

    INSERT INTO feature_flags (
      flag_key,
      display_name,
      description,
      is_enabled,
      flag_type,
      default_value,
      requires_app_restart,
      min_app_version,
      created_at,
      updated_at
    )
    SELECT
      'inventory_ledger_reads',
      'Inventory Ledger Reads',
      'Lê saldos do cache stock_balances em vez do cálculo legado.',
      false,
      'boolean',
      'false',
      false,
      NULL,
      now(),
      now()
    WHERE NOT EXISTS (
      SELECT 1 FROM feature_flags WHERE flag_key = 'inventory_ledger_reads'
    );
  END IF;
END $$;
"""
    )


def downgrade():
    op.execute(
        """
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'feature_flags') THEN
    DELETE FROM feature_flags
    WHERE flag_key IN ('inventory_ledger_dual_write', 'inventory_ledger_reads');
  END IF;

  DROP TABLE IF EXISTS stock_balances;
  DROP TABLE IF EXISTS stock_movements;
END $$;
"""
    )