"""Add stock entry documents and document items

Revision ID: c3f9a6e1b2d4
Revises: 9f2c6a1d0b7e
Create Date: 2026-03-16
"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "c3f9a6e1b2d4"
down_revision = "9f2c6a1d0b7e"
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        """
DO $$
BEGIN
  CREATE TABLE IF NOT EXISTS entrada_documentos (
    id_documento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id integer NULL REFERENCES finance_fornecedores(id),
    tipo_documento varchar(40) NOT NULL DEFAULT 'nf',
    numero_documento varchar(120) NOT NULL,
    data_emissao date NULL,
    data_recebimento date NULL,
    cnpj_emitente varchar(18) NULL,
    fornecedor_nome varchar(200) NULL,
    observacao text NULL,
    criado_por varchar(100) NULL,
    criado_em timestamp NOT NULL DEFAULT now(),
    atualizado_em timestamp NOT NULL DEFAULT now()
  );

  CREATE TABLE IF NOT EXISTS entrada_documento_itens (
    id_documento_item integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id integer NOT NULL REFERENCES entrada_documentos(id_documento) ON DELETE CASCADE,
    entrada_id integer NULL REFERENCES entradas(id_entrada),
    codigo_item varchar NOT NULL REFERENCES itens(codigo_item),
    quantidade double precision NOT NULL DEFAULT 0,
    valor_unitario double precision NULL,
    valor_total double precision NULL,
    lote varchar(50) NULL,
    data_validade date NULL,
    observacao text NULL,
    criado_em timestamp NOT NULL DEFAULT now()
  );

  CREATE INDEX IF NOT EXISTS ix_entrada_documentos_numero ON entrada_documentos(numero_documento);
  CREATE INDEX IF NOT EXISTS ix_entrada_documentos_fornecedor ON entrada_documentos(fornecedor_id);
  CREATE INDEX IF NOT EXISTS ix_entrada_documentos_emissao ON entrada_documentos(data_emissao);
  CREATE INDEX IF NOT EXISTS ix_entrada_documento_itens_documento ON entrada_documento_itens(documento_id);
  CREATE INDEX IF NOT EXISTS ix_entrada_documento_itens_item ON entrada_documento_itens(codigo_item);
  CREATE INDEX IF NOT EXISTS ix_entrada_documento_itens_entrada ON entrada_documento_itens(entrada_id);
END $$;
"""
    )


def downgrade():
    op.execute(
        """
DO $$
BEGIN
  DROP TABLE IF EXISTS entrada_documento_itens;
  DROP TABLE IF EXISTS entrada_documentos;
END $$;
"""
    )