"""add immutable fiscal entry history

Revision ID: f1a2b3c4d5e6
Revises: e8a1f3c4d2b7
"""
from alembic import op

revision = "f1a2b3c4d5e6"
down_revision = "d5e6f7a8b9c1"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
    CREATE TABLE IF NOT EXISTS entradas_fiscais_historico (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      evento varchar(30) NOT NULL,
      ocorrido_em timestamp NOT NULL DEFAULT now(),
      documento_id integer NULL,
      documento_item_id integer NULL,
      codigo_item varchar NOT NULL,
      descricao_item text NULL,
      marca_item varchar(200) NULL,
      categoria_item varchar(120) NULL,
      tipo_documento varchar(40) NOT NULL,
      numero_documento varchar(120) NOT NULL,
      chave_acesso varchar(64) NULL,
      data_emissao date NULL,
      data_recebimento date NULL,
      quantidade double precision NOT NULL DEFAULT 0,
      unidade_quantidade varchar(30) NULL,
      quantidade_base double precision NULL,
      valor_unitario double precision NULL,
      valor_unitario_base double precision NULL,
      unidade_preco varchar(30) NULL,
      valor_total double precision NULL,
      lote varchar(50) NULL,
      data_validade date NULL,
      status_processamento varchar(30) NULL,
      motivo text NULL,
      usuario_matricula varchar(100) NULL
    );
    CREATE INDEX IF NOT EXISTS ix_entradas_fiscais_historico_codigo ON entradas_fiscais_historico(codigo_item);
    CREATE INDEX IF NOT EXISTS ix_entradas_fiscais_historico_numero ON entradas_fiscais_historico(numero_documento);
    CREATE INDEX IF NOT EXISTS ix_entradas_fiscais_historico_chave ON entradas_fiscais_historico(chave_acesso);
    INSERT INTO entradas_fiscais_historico (
      evento, documento_id, documento_item_id, codigo_item, descricao_item,
      marca_item, categoria_item, tipo_documento, numero_documento, chave_acesso,
      data_emissao, data_recebimento, quantidade, unidade_quantidade,
      quantidade_base, valor_unitario, valor_unitario_base, unidade_preco,
      valor_total, lote, data_validade, status_processamento
    )
    SELECT 'entrada_legada', d.id_documento, di.id_documento_item, di.codigo_item,
      i.descricao, i.marca, i.categoria, d.tipo_documento, d.numero_documento,
      d.chave_acesso, d.data_emissao, d.data_recebimento, di.quantidade,
      di.unidade_quantidade, di.quantidade_base, di.valor_unitario,
      di.valor_unitario_base, di.unidade_preco, di.valor_total, di.lote,
      di.data_validade, di.status_processamento
    FROM entrada_documento_itens di
    JOIN entrada_documentos d ON d.id_documento = di.documento_id
    LEFT JOIN itens i ON i.codigo_item = di.codigo_item
    WHERE NOT EXISTS (
      SELECT 1 FROM entradas_fiscais_historico h
      WHERE h.documento_item_id = di.id_documento_item AND h.evento = 'entrada_legada'
    );

    INSERT INTO entradas_fiscais_historico (
      evento, documento_id, documento_item_id, codigo_item, descricao_item,
      tipo_documento, numero_documento, data_recebimento, quantidade,
      status_processamento
    )
    SELECT 'entrada_legada', NULL, e.id_entrada, e.codigo_item, i.descricao,
      'nf', COALESCE(NULLIF(e.nota_fiscal, ''), 'ENTRADA LEGADA'),
      CAST(e.data_entrada AS date), e.quantidade, 'processado'
    FROM entradas e
    LEFT JOIN itens i ON i.codigo_item = e.codigo_item
    WHERE e.nota_fiscal IS NOT NULL AND btrim(e.nota_fiscal) <> ''
      AND NOT EXISTS (
        SELECT 1 FROM entradas_fiscais_historico h
        WHERE h.documento_item_id = e.id_entrada AND h.evento = 'entrada_legada'
      );
    """)


def downgrade():
    op.execute("DROP TABLE IF EXISTS entradas_fiscais_historico")