"""Add GalintNotify router and inbox tables

Revision ID: f8b1d9c2a6e4
Revises: b1a4d2f9c8e7
Create Date: 2026-03-20
"""

from alembic import op


revision = "f8b1d9c2a6e4"
down_revision = "b1a4d2f9c8e7"
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        """
DO $$
BEGIN
  CREATE TABLE IF NOT EXISTS notification_router_config (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    default_channel varchar(20) NOT NULL DEFAULT 'telegram',
    telegram_enabled boolean NOT NULL DEFAULT true,
    notify_enabled boolean NOT NULL DEFAULT true,
    push_provider varchar(20) NOT NULL DEFAULT 'expo',
    push_enabled boolean NOT NULL DEFAULT true,
    circuit_fail_threshold integer NOT NULL DEFAULT 2,
    circuit_timeout_seconds integer NOT NULL DEFAULT 10,
    circuit_cooldown_seconds integer NOT NULL DEFAULT 120,
    telegram_fail_count integer NOT NULL DEFAULT 0,
    telegram_last_error text NULL,
    telegram_last_failure_at timestamp NULL,
    telegram_last_success_at timestamp NULL,
    telegram_unhealthy_until timestamp NULL,
    updated_at timestamp NOT NULL DEFAULT now()
  );

  CREATE TABLE IF NOT EXISTS galint_notify_messages (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category varchar(80) NOT NULL DEFAULT 'general',
    message_type varchar(80) NOT NULL DEFAULT 'info',
    title varchar(200) NOT NULL,
    body text NOT NULL,
    payload jsonb NULL,
    created_at timestamp NOT NULL DEFAULT now()
  );

  CREATE TABLE IF NOT EXISTS galint_notify_recipients (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id integer NOT NULL REFERENCES galint_notify_messages(id) ON DELETE CASCADE,
    matricula varchar NOT NULL REFERENCES usuarios(matricula) ON DELETE CASCADE,
    status varchar(20) NOT NULL DEFAULT 'unread',
    delivered_at timestamp NULL,
    read_at timestamp NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT uq_notify_message_recipient UNIQUE (message_id, matricula)
  );

  CREATE TABLE IF NOT EXISTS device_push_tokens (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula varchar NOT NULL REFERENCES usuarios(matricula) ON DELETE CASCADE,
    device_uuid varchar(120) NOT NULL,
    provider varchar(20) NOT NULL DEFAULT 'expo',
    token text NOT NULL,
    ativo boolean NOT NULL DEFAULT true,
    last_error text NULL,
    last_push_at timestamp NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT uq_device_push_provider UNIQUE (device_uuid, provider)
  );

  CREATE INDEX IF NOT EXISTS ix_notify_recipients_matricula ON galint_notify_recipients(matricula);
  CREATE INDEX IF NOT EXISTS ix_notify_recipients_status ON galint_notify_recipients(status);
  CREATE INDEX IF NOT EXISTS ix_notify_messages_created_at ON galint_notify_messages(created_at DESC);
  CREATE INDEX IF NOT EXISTS ix_device_push_tokens_matricula ON device_push_tokens(matricula);
  CREATE INDEX IF NOT EXISTS ix_device_push_tokens_active ON device_push_tokens(ativo);

  ALTER TABLE notification_router_config ALTER COLUMN default_channel SET DEFAULT 'telegram';
  ALTER TABLE notification_router_config ALTER COLUMN telegram_enabled SET DEFAULT true;
  ALTER TABLE notification_router_config ALTER COLUMN notify_enabled SET DEFAULT true;
  ALTER TABLE notification_router_config ALTER COLUMN push_provider SET DEFAULT 'expo';
  ALTER TABLE notification_router_config ALTER COLUMN push_enabled SET DEFAULT true;
  ALTER TABLE notification_router_config ALTER COLUMN circuit_fail_threshold SET DEFAULT 2;
  ALTER TABLE notification_router_config ALTER COLUMN circuit_timeout_seconds SET DEFAULT 10;
  ALTER TABLE notification_router_config ALTER COLUMN circuit_cooldown_seconds SET DEFAULT 120;
  ALTER TABLE notification_router_config ALTER COLUMN telegram_fail_count SET DEFAULT 0;
  ALTER TABLE notification_router_config ALTER COLUMN updated_at SET DEFAULT now();

  IF NOT EXISTS (SELECT 1 FROM notification_router_config WHERE id = 1) THEN
    INSERT INTO notification_router_config (
      id,
      default_channel,
      telegram_enabled,
      notify_enabled,
      push_provider,
      push_enabled,
      circuit_fail_threshold,
      circuit_timeout_seconds,
      circuit_cooldown_seconds,
      telegram_fail_count,
      updated_at
    )
    VALUES (1, 'telegram', true, true, 'expo', true, 2, 10, 120, 0, now());
  END IF;
END $$;
"""
    )


def downgrade():
    op.execute(
        """
DO $$
BEGIN
  DROP TABLE IF EXISTS device_push_tokens;
  DROP TABLE IF EXISTS galint_notify_recipients;
  DROP TABLE IF EXISTS galint_notify_messages;
  DROP TABLE IF EXISTS notification_router_config;
END $$;
"""
    )