"""autogenerated by app.py

Revision ID: 95c17ef714ba
Revises: 
Create Date: 2025-12-16 14:06:35.755174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c17ef714ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_config', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'low_stock_enabled',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('false'),
            )
        )
        batch_op.add_column(
            sa.Column(
                'low_stock_weekly_count',
                sa.Integer(),
                nullable=False,
                server_default=sa.text('3'),
            )
        )
        batch_op.add_column(
            sa.Column(
                'low_stock_daily_count',
                sa.Integer(),
                nullable=False,
                server_default=sa.text('3'),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_config', schema=None) as batch_op:
        batch_op.drop_column('low_stock_daily_count')
        batch_op.drop_column('low_stock_weekly_count')
        batch_op.drop_column('low_stock_enabled')

    # ### end Alembic commands ###
